// <auto-generated />
using Crawler.Persistence.Local;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Crawler.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210520194441_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("Crawler.Domain.Entities.Pointer", b =>
                {
                    b.Property<string>("Identifier")
                        .HasColumnType("TEXT");

                    b.HasKey("Identifier");

                    b.ToTable("Pointers");
                });
#pragma warning restore 612, 618
        }
    }
}
