version: '3.1'

services:
  crawler:
    image: crawler:latest
    depends_on:
      - "mongo"
    volumes:
      - "./appsettings.json:/app/appsettings.json"

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root